README: Add detailed contributions nformation
agherzan/meta-chip pull request #13
Opened 2017-06-29 15:47 UTC by agherzan

Signed-off-by: Andrei Gherzan <andrei@gherzan.com>

2017-06-29 15:49 UTC, twoerner commented
nformation -> information

2017-06-29 19:00 UTC, twoerner requested changes

2017-06-29 19:00 UTC, twoerner commented on README
> +more people can see and review your contributions..
too many "people"

2017-06-29 19:58 UTC, agherzan commented on README
> +more people can see and review your contributions..
Let all the people review! Copy paste is not an amazing method of doing stuff.

2017-07-04 15:51 UTC, agherzan commented on README
> +more people can see and review your contributions..
@twoerner fixed. Thanks.

2017-07-05 11:12 UTC, agherzan commented
@twoerner looks good now?

2017-07-05 12:41 UTC, twoerner commented
@agherzan yes, looks great, thanks 👍

2017-07-05 12:44 UTC, agherzan commented
@twoerner let's unblock the PR with a approved review :)

2017-07-05 13:02 UTC, twoerner approved these changes
LGTM

2017-07-05 13:02 UTC, twoerner commented
For me, the github page says: "At least one approved review is required by reviewers with write access." Since I don't have write access to this repository, I assumed that wasn't for me.

2017-07-05 13:44 UTC, agherzan commented
@twoerner that makes sense.

2017-07-05 13:44 UTC, merged