Flashing instructions v2
agherzan/meta-chip pull request #9
Opened 2017-06-26 13:52 UTC by drewmoseley

This PR was recently submitted to the Yocto mailing list and based on the post from @agherzan to suggest using Github PRs and Jenkins I figured I'd give that a shot here.

2017-06-26 14:33 UTC, agherzan commented
I'm setting up the jenkins server as we speak. This will be the first PR testing it.

2017-06-26 15:13 UTC, agherzan commented
ok to test

2017-06-26 15:29 UTC, agherzan commented
test this please

2017-06-26 16:10 UTC, agherzan requested changes

2017-06-26 16:10 UTC, agherzan commented on conf/layer.conf
> +LAYERDEPENDS_meta-chip = "meta-sunxi"
A new line would be nice here.

2017-06-26 16:10 UTC, agherzan commented on recipes-bsp/u-boot/u-boot-chip_git.bb
> +}
New line please.

2017-06-26 16:10 UTC, agherzan commented on README
> +    # UBI_IMAGE=chip-hwup-image-chip.ubi ./build/chip/tmp/deploy/images/chip/flash_CHIP_board.sh
A little bit of inconsistency here. We use a path which includes the build directory while above we use a path inside this directory. Would be nice to have them both with or without build directory.

2017-06-26 16:10 UTC, agherzan commented on README
> +system. More details here:
I would reword this to something like "to your host".

2017-06-26 16:10 UTC, agherzan commented on README
> +board.  Note that this script assumes a maximum size for your UBI
This text introduces from time to time double spaces. Would be nice to have them fixed.

2017-06-26 16:10 UTC, agherzan commented on recipes-bsp/chip-u-boot-scr/chip-u-boot-scr.bb
> +COMPATIBLE_MACHINE = "chip"
Usually the COMPATIBLE_MACHINE is at the end of the recipe: https://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta-skeleton/recipes-kernel/linux/linux-yocto-custom.bb .

2017-06-26 16:10 UTC, agherzan commented on recipes-bsp/chip-u-boot-scr/chip-u-boot-scr.bb
> +do_compile[depends] += "u-boot-chip:do_deploy"
Wouldn't DEPEND on u-boot-chip suffice?

2017-06-26 16:10 UTC, agherzan commented on recipes-bsp/chip-u-boot-scr/chip-u-boot-scr.bb
> +PAGE_SIZE = "16384"
We have this value defined in the machine configuration already. Could we use it from there (define it there and use it in both `MKUBIFS_ARGS` and here)?.

2017-06-27 08:47 UTC, koenkooi commented on recipes-bsp/chip-u-boot-scr/chip-u-boot-scr.bb
> +do_compile[depends] += "u-boot-chip:do_deploy"
No, DEPENDS is shorthand for "recipe:do_populate_sysroot", not "recipe:do_build"

2017-06-27 08:51 UTC, koenkooi commented
This script is great for flashing from scratch, but it does have some drawbacks. What would be nice, but is something for a follow up PR, is the following:

1) Allow to only flash the rootfs (as in: ubi volume)
2) Use the builtin ubi tools in uboot to keep the erase counters and bad block map.

The NAND used on the CHIP is very prone to errors or just hates UBIFS, so keeping at least the bad block map would be very helpful.

2017-06-27 10:37 UTC, koenkooi commented
And find a way to fix #11

2017-06-27 13:13 UTC, agherzan commented on recipes-bsp/chip-u-boot-scr/chip-u-boot-scr.bb
> +do_compile[depends] += "u-boot-chip:do_deploy"
Good point.

2017-06-29 01:16 UTC, drewmoseley commented
I pushed updated commits to the existing branch to address the review comments.  I think I made all the requested changes.  Please let me know if I missed anything.

This has also been sent to the mailing list as V3.  I guess embedding the version in the git branch and PR title is not a good approach.

2017-06-29 15:36 UTC, agherzan approved these changes

2017-06-29 15:36 UTC, agherzan commented
@drewmoseley Don't worry about the branch name - it's good though to avoid it in the future. Looks good now the PR so I'll merge it. Thanks for your work.

2017-06-29 15:37 UTC, merged